services:
    madrak_io_easy_admin.crud_view_twig_extension:
        class: MadrakIO\Bundle\EasyAdminBundle\CrudView\CrudViewTwigExtension
        public: false
        tags:
            - { name: twig.extension }
    madrak_io_easy_admin.field_type_chain:
        class: MadrakIO\Bundle\EasyAdminBundle\Chain\FieldTypeChain
    madrak_io_easy_admin.field_type_guesser:
        class: MadrakIO\Bundle\EasyAdminBundle\CrudView\Guesser\FieldTypeGuesser
        arguments: ['@madrak_io_easy_admin.field_type_chain']
    madrak_io_easy_admin.controller_chain:
        class: MadrakIO\Bundle\EasyAdminBundle\Chain\ControllerChain
    madrak_io_easy_admin.crud_list_type:
        abstract: true
        arguments:
            - '@templating'
            - '@doctrine.orm.default_entity_manager'
            - '@security.authorization_checker'
            - '@madrak_io_easy_admin.field_type_guesser'
            - '@form.factory'
        calls:
            - [ setCheckGrants, [ '%madrak_io_easy_admin.check_grants%' ]]
    madrak_io_easy_admin.crud_show_type:
        abstract: true
        arguments:
            - '@templating'
            - '@doctrine.orm.default_entity_manager'
            - '@madrak_io_easy_admin.field_type_guesser'
    madrak_io_easy_admin.crud_controller:
        abstract: true
        calls:
            - [ setContainer, [ "@service_container" ]]
    madrak_io_easy_admin.dashboard_controller:
        abstract: true
        calls:
            - [ setContainer, [ "@service_container" ]]
